travis: use PHPUnit 6
This is what WordPress does, and using PHPUnit 5 is currently giving us
errors, so we'd though we'd go ahead and try updating.

```
$ phpunit-basic
Not running plugin install/uninstall tests... To execute these, use -c phpunit.uninstall.xml.dist.
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.

PHP Fatal error:  Uncaught PHPUnit_Framework_Exception: Class "PHPUnit_Framework_TestSuite_DataProvider" does not extend PHPUnit_Framework_TestCase.
  thrown in /home/travis/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php on line 147

Fatal error: Uncaught PHPUnit_Framework_Exception: Class "PHPUnit_Framework_TestSuite_DataProvider" does not extend PHPUnit_Framework_TestCase.
  thrown in /home/travis/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php on line 147

PHPUnit_Framework_Exception: Class "PHPUnit_Framework_TestSuite_DataProvider" does not extend PHPUnit_Framework_TestCase. in /home/travis/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php on line 147

Call Stack:
    0.0002     375560   1. {main}() /home/travis/.composer/vendor/phpunit/phpunit/phpunit:0
    0.0043     723248   2. PHPUnit_TextUI_Command::main() /home/travis/.composer/vendor/phpunit/phpunit/phpunit:52
    0.0043     726408   3. PHPUnit_TextUI_Command->run() /home/travis/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:116
    0.0043     726408   4. PHPUnit_TextUI_Command->handleArguments() /home/travis/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:127
    3.1850   32037776   5. PHPUnit_Util_Configuration->getTestSuiteConfiguration() /home/travis/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:784
    3.1850   32038360   6. PHPUnit_Util_Configuration->getTestSuite() /home/travis/.composer/vendor/phpunit/phpunit/src/Util/Configuration.php:843
    3.2210   32261024   7. PHPUnit_Framework_TestSuite->addTestFiles() /home/travis/.composer/vendor/phpunit/phpunit/src/Util/Configuration.php:946
    3.2291   32943352   8. PHPUnit_Framework_TestSuite->addTestFile() /home/travis/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:389
    3.2311   33233576   9. PHPUnit_Framework_TestSuite->addTestSuite() /home/travis/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:363
    3.2311   33234032  10. PHPUnit_Framework_TestSuite->__construct() /home/travis/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:281
```